import type { AICall, Customer, Job, Technician } from './types';

export const technicians: Technician[] = [
  { id: 't1', name: 'Marcus Reed', initials: 'MR', color: '#2563EB', trade: 'HVAC', jobsToday: 4 },
  { id: 't2', name: 'Diana Cruz', initials: 'DC', color: '#16A34A', trade: 'Plumbing', jobsToday: 3 },
  { id: 't3', name: 'Sam Patel', initials: 'SP', color: '#D97706', trade: 'Electrical', jobsToday: 5 },
  { id: 't4', name: 'Jess Nakamura', initials: 'JN', color: '#7C3AED', trade: 'HVAC', jobsToday: 2 },
];

export const customers: Customer[] = [
  {
    id: 'c1',
    name: 'Linda Hernandez',
    phone: '(512) 555-0182',
    email: 'linda.h@gmail.com',
    address: '4421 Bouldin Ave, Austin TX 78704',
    notes: 'Two cats. Prefers afternoon appointments.',
    lifetimeValue: 4820,
    jobCount: 7,
  },
  {
    id: 'c2',
    name: 'Brennan Coffee Roasters',
    phone: '(512) 555-0144',
    email: 'ops@brennancoffee.co',
    address: '900 E 5th St, Austin TX 78702',
    notes: 'Commercial. After hours preferred (close at 6pm).',
    lifetimeValue: 18950,
    jobCount: 12,
  },
  {
    id: 'c3',
    name: 'Marcus Wong',
    phone: '(512) 555-0119',
    email: 'mwong@hey.com',
    address: '2207 Westlake Dr, Austin TX 78746',
    lifetimeValue: 1200,
    jobCount: 2,
  },
  {
    id: 'c4',
    name: 'Sage Apartments',
    phone: '(512) 555-0177',
    email: 'maintenance@sageapts.com',
    address: '6010 Burnet Rd, Austin TX 78757',
    notes: 'Property mgmt. Master account. NET 30.',
    lifetimeValue: 42100,
    jobCount: 31,
  },
  {
    id: 'c5',
    name: 'Priya Shah',
    phone: '(512) 555-0166',
    email: 'priya.shah@outlook.com',
    address: '1819 Kinney Ave, Austin TX 78704',
    lifetimeValue: 750,
    jobCount: 1,
  },
];

const today = new Date();
const at = (hours: number, minutes = 0) => {
  const d = new Date(today);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};

export const jobs: Job[] = [
  {
    id: 'j1',
    customerId: 'c1',
    trade: 'HVAC',
    title: 'AC not cooling — second floor',
    description:
      'Customer reports upstairs unit blowing warm air since last night. System is ~8 years old. Suspect refrigerant leak or failed capacitor.',
    status: 'en_route',
    priority: 'emergency',
    scheduledFor: at(9, 30),
    technicianId: 't1',
    estimatedMinutes: 90,
    createdVia: 'ai_voice',
    lineItems: [],
    notes: ['Customer at home until 2pm.', 'Two cats — keep door closed.'],
  },
  {
    id: 'j2',
    customerId: 'c2',
    trade: 'Plumbing',
    title: 'Espresso machine drain backup',
    description:
      'Floor drain behind bar overflowing during morning rush. Need cleared before 6am tomorrow.',
    status: 'scheduled',
    priority: 'emergency',
    scheduledFor: at(18, 30),
    technicianId: 't2',
    estimatedMinutes: 120,
    createdVia: 'ai_voice',
    lineItems: [],
    notes: ['After-hours job.', 'Manager Brennan will meet on site.'],
  },
  {
    id: 'j3',
    customerId: 'c3',
    trade: 'HVAC',
    title: 'Annual maintenance — 2 systems',
    description: 'Spring tune-up on both upstairs and downstairs Trane units.',
    status: 'completed',
    priority: 'maintenance',
    scheduledFor: at(8, 0),
    technicianId: 't4',
    estimatedMinutes: 75,
    createdVia: 'recurring',
    lineItems: [
      { id: 'l1', description: 'Maintenance plan visit (2 systems)', quantity: 1, unitPrice: 189, taxable: true },
      { id: 'l2', description: 'Replaced 16x25x1 filters (2)', quantity: 2, unitPrice: 14, taxable: true },
    ],
    notes: ['Recommended capacitor replacement on downstairs unit next visit.'],
  },
  {
    id: 'j4',
    customerId: 'c4',
    trade: 'Electrical',
    title: 'Unit 312 — outlets dead in kitchen',
    description: 'Tenant reports all outlets on east wall non-functional. Likely tripped breaker or GFCI.',
    status: 'in_progress',
    priority: 'standard',
    scheduledFor: at(11, 0),
    technicianId: 't3',
    estimatedMinutes: 60,
    createdVia: 'web_form',
    lineItems: [],
    notes: ['Property manager has master key.'],
  },
  {
    id: 'j5',
    customerId: 'c5',
    trade: 'Plumbing',
    title: 'Kitchen faucet replacement',
    description: 'Customer purchased Delta 9159T-AR-DST. Needs install + haul-away of old fixture.',
    status: 'invoiced',
    priority: 'standard',
    scheduledFor: at(14, 0),
    technicianId: 't2',
    estimatedMinutes: 60,
    createdVia: 'manual',
    lineItems: [
      { id: 'l3', description: 'Faucet installation labor', quantity: 1, unitPrice: 245, taxable: true },
      { id: 'l4', description: 'Haul-away fee', quantity: 1, unitPrice: 35, taxable: true },
      { id: 'l5', description: 'Supply line replacement (pair)', quantity: 1, unitPrice: 28, taxable: true },
    ],
    notes: [],
  },
  {
    id: 'j6',
    customerId: 'c4',
    trade: 'HVAC',
    title: 'Unit 207 — thermostat replacement',
    description: 'Replace failed Honeywell with property-spec Ecobee Lite.',
    status: 'scheduled',
    priority: 'standard',
    scheduledFor: at(15, 30),
    technicianId: 't1',
    estimatedMinutes: 45,
    createdVia: 'web_form',
    lineItems: [],
    notes: [],
  },
];

export const aiCalls: AICall[] = [
  {
    id: 'a1',
    callerName: 'Linda Hernandez',
    callerPhone: '(512) 555-0182',
    startedAt: at(7, 12),
    durationSeconds: 142,
    outcome: 'job_booked',
    jobId: 'j1',
    summary:
      'Existing customer. Upstairs AC blowing warm air overnight. Booked emergency 9:30am visit with Marcus. Confirmed two cats on file.',
    transcript: [
      { speaker: 'agent', at: 0, text: "Thanks for calling Austin Air & Plumbing, this is Ava. How can I help?" },
      { speaker: 'caller', at: 4, text: "Hi, my upstairs AC is blowing warm air and it's already 80 in here." },
      { speaker: 'agent', at: 9, text: "I'm sorry, that's miserable in this heat. Can I get the phone number on the account?" },
      { speaker: 'caller', at: 14, text: "Sure, 512-555-0182." },
      { speaker: 'agent', at: 18, text: "Got it, is this Linda over on Bouldin Ave?" },
      { speaker: 'caller', at: 22, text: "Yes, that's me." },
      { speaker: 'agent', at: 24, text: "Perfect. I see Marcus did your spring tune-up. I can get him out today between 9:30 and 10:30. Does that work?" },
      { speaker: 'caller', at: 32, text: "Yes please, the sooner the better." },
      { speaker: 'agent', at: 35, text: "Booked. Diagnostic fee is $89, waived if you proceed with the repair. I noted the two cats — we'll keep doors closed. Anything else?" },
      { speaker: 'caller', at: 46, text: "No, thank you so much." },
      { speaker: 'agent', at: 48, text: "Of course. You'll get a text when Marcus is on the way. Have a good morning." },
    ],
  },
  {
    id: 'a2',
    callerName: 'Unknown',
    callerPhone: '(737) 555-0291',
    startedAt: at(6, 48),
    durationSeconds: 88,
    outcome: 'quote_requested',
    summary:
      'New caller asked for tankless water heater install quote. Captured contact, scheduled in-home estimate Wednesday 2pm.',
    transcript: [
      { speaker: 'agent', at: 0, text: "Thanks for calling Austin Air & Plumbing, this is Ava." },
      { speaker: 'caller', at: 3, text: "Hi, I'd like a quote on a tankless water heater for my house." },
      { speaker: 'agent', at: 8, text: "Happy to help. Are you replacing an existing tank or doing new install?" },
      { speaker: 'caller', at: 13, text: "Replacing a 50-gallon tank in the garage." },
      { speaker: 'agent', at: 17, text: "Got it. For tankless we send a tech out for a free estimate so we can size it right. Are you available Wednesday at 2pm?" },
      { speaker: 'caller', at: 26, text: "Wednesday works." },
      { speaker: 'agent', at: 28, text: "Great, can I get your name, address, and email?" },
    ],
  },
  {
    id: 'a3',
    callerName: 'Brennan Coffee',
    callerPhone: '(512) 555-0144',
    startedAt: at(5, 31),
    durationSeconds: 67,
    outcome: 'job_booked',
    jobId: 'j2',
    summary:
      'Commercial customer — drain backup behind bar. After-hours emergency booked for 6:30pm tonight with Diana.',
    transcript: [
      { speaker: 'agent', at: 0, text: "Austin Air & Plumbing, this is Ava." },
      { speaker: 'caller', at: 2, text: "It's Brennan at the coffee shop. The bar drain is overflowing again." },
      { speaker: 'agent', at: 6, text: "Oh no. I have you for after-hours — does 6:30 tonight work? Diana can be there." },
      { speaker: 'caller', at: 12, text: "Perfect, see her then." },
    ],
  },
];
