import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card } from '../../src/components/Card';
import { duration, time } from '../../src/format';
import { useStore } from '../../src/store';
import { theme } from '../../src/theme';

export default function CallDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const call = useStore((s) => s.aiCalls.find((c) => c.id === id));
  const linkedJob = useStore((s) => (call?.jobId ? s.jobs.find((j) => j.id === call.jobId) : undefined));

  if (!call) {
    return (
      <View style={styles.empty}>
        <Text>Call not found</Text>
      </View>
    );
  }

  return (
    <ScrollView style={{ backgroundColor: theme.colors.bg }} contentContainerStyle={{ paddingBottom: 32 }}>
      <Card style={styles.headerCard}>
        <View style={styles.headerRow}>
          <View style={styles.iconWrap}>
            <Ionicons name="call" size={22} color={theme.colors.accent} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.name}>{call.callerName}</Text>
            <Text style={styles.phone}>{call.callerPhone}</Text>
          </View>
        </View>
        <View style={styles.metaRow}>
          <Meta icon="time-outline" label={time(call.startedAt)} />
          <Meta icon="hourglass-outline" label={duration(call.durationSeconds)} />
        </View>
      </Card>

      <Text style={styles.sectionLabel}>AI summary</Text>
      <Card style={styles.summaryCard}>
        <View style={styles.summaryHeader}>
          <Ionicons name="sparkles" size={14} color={theme.colors.accent} />
          <Text style={styles.summaryHeaderText}>Generated by Ava</Text>
        </View>
        <Text style={styles.summaryText}>{call.summary}</Text>
      </Card>

      {linkedJob && (
        <>
          <Text style={styles.sectionLabel}>Linked job</Text>
          <Pressable onPress={() => router.push(`/job/${linkedJob.id}`)}>
            <Card style={styles.linkedJobCard}>
              <View style={{ flex: 1 }}>
                <Text style={styles.linkedJobTitle}>{linkedJob.title}</Text>
                <Text style={styles.linkedJobSub}>
                  {linkedJob.trade} · {time(linkedJob.scheduledFor)}
                </Text>
              </View>
              <Ionicons name="chevron-forward" size={20} color={theme.colors.textMuted} />
            </Card>
          </Pressable>
        </>
      )}

      <Text style={styles.sectionLabel}>Transcript</Text>
      <View style={styles.transcript}>
        {call.transcript.map((turn, i) => {
          const isAgent = turn.speaker === 'agent';
          return (
            <View key={i} style={[styles.turn, isAgent ? styles.turnLeft : styles.turnRight]}>
              <View style={[styles.bubble, isAgent ? styles.bubbleAgent : styles.bubbleCaller]}>
                <Text style={[styles.bubbleLabel, isAgent ? { color: theme.colors.accent } : { color: theme.colors.primary }]}>
                  {isAgent ? 'AVA' : call.callerName.toUpperCase()}
                </Text>
                <Text style={styles.bubbleText}>{turn.text}</Text>
                <Text style={styles.bubbleTime}>{turn.at}s</Text>
              </View>
            </View>
          );
        })}
      </View>
    </ScrollView>
  );
}

function Meta({ icon, label }: { icon: any; label: string }) {
  return (
    <View style={styles.meta}>
      <Ionicons name={icon} size={14} color={theme.colors.textMuted} />
      <Text style={styles.metaText}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  headerCard: { margin: theme.spacing.lg, gap: theme.spacing.md },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md },
  iconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: { fontSize: theme.font.lg, fontWeight: '700', color: theme.colors.text },
  phone: { fontSize: theme.font.sm, color: theme.colors.textMuted, marginTop: 2 },
  metaRow: { flexDirection: 'row', gap: theme.spacing.lg },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontSize: theme.font.sm, color: theme.colors.textMuted },
  sectionLabel: {
    fontSize: theme.font.sm,
    fontWeight: '700',
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  summaryCard: {
    marginHorizontal: theme.spacing.lg,
    backgroundColor: '#FAF9FF',
    borderColor: theme.colors.accentSoft,
    borderWidth: 1.5,
    gap: theme.spacing.sm,
  },
  summaryHeader: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  summaryHeaderText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.accent,
    letterSpacing: 0.4,
  },
  summaryText: { fontSize: theme.font.md, color: theme.colors.text, lineHeight: 21 },
  linkedJobCard: {
    marginHorizontal: theme.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  linkedJobTitle: { fontSize: theme.font.md, fontWeight: '600', color: theme.colors.text },
  linkedJobSub: { fontSize: theme.font.sm, color: theme.colors.textMuted, marginTop: 2 },
  transcript: { paddingHorizontal: theme.spacing.lg, gap: theme.spacing.sm },
  turn: { flexDirection: 'row' },
  turnLeft: { justifyContent: 'flex-start' },
  turnRight: { justifyContent: 'flex-end' },
  bubble: {
    maxWidth: '82%',
    padding: theme.spacing.md,
    borderRadius: theme.radius.lg,
    gap: 4,
  },
  bubbleAgent: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  bubbleCaller: {
    backgroundColor: theme.colors.primarySoft,
    borderTopRightRadius: 4,
  },
  bubbleLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 0.6 },
  bubbleText: { fontSize: theme.font.md, color: theme.colors.text, lineHeight: 20 },
  bubbleTime: { fontSize: 10, color: theme.colors.textSubtle, marginTop: 2 },
});
